spring:
  application:
    name: catalog-service

  config:
    import: "optional:configserver:"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: root

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/catalogdb
    user: postgres
    password: root
    schemas: public
    baseline-on-migrate: true
    locations: classpath:db/migration


  main:
    web-application-type: reactive

  jackson:
    serialization:
      indent-output: true


server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.flywaydb: DEBUG
