version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: arka-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
