version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: catalog-postgres
    restart: always
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - catalog_pg_data:/var/lib/postgresql/data

volumes:
  catalog_pg_data:
